apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: iydt85a4l-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:f3b15301b8c9db8b41e62a9aedf0f8cc276370d7@sha256:e71c4d438ef0ac71fe15c470b9e6bedc599f7e6e548888e3b4eb69d758ec0a27
          name: container-image
